# Generated by Django 4.1.2 on 2022-10-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
