# Generated by Django 4.1.2 on 2022-10-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttimelog",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
